int parseFilters(char *, char *);
int filterMenu(int *, int *);
int printNotifLines(WINDOW *, notif_line_ptr, int, int, int);
int getSetsForNotifs(hash_set_ptr, hash_set_ptr, hash_set_ptr, int *);
int addLinesToNotifications(WINDOW *, hash_set_ptr, notif_line_ptr, int, int *, int *);
void notificationsWindow(void *);
int notificationsMenu(int *, int *);
notif_line_ptr getNewNotifsLinePtr();
int freeAllPsLines(ps_line_ptr);
int freePsLinePtr(ps_line_ptr);
ps_line_ptr getNewPsLinePtr();
int refreshRateMenu(int *, int *);
hash_set_ptr getNewHashSet();
int freeHashSet(hash_set_ptr);
unsigned long hashProcName(char *);
int setContainsByHash(hash_set_ptr, unsigned long, long long);
int setContainsByName(hash_set_ptr, char *, long long);
int addProcToSetByName(hash_set_ptr, char *, long long);
int removeProcFromSetByName(hash_set_ptr, char *, long long);
int addProcToSetByHash(hash_set_ptr, unsigned long, long long);
int removeProcFromSetByHash(hash_set_ptr, unsigned long, long long);
hash_set_ptr compareSets(hash_set_ptr, hash_set_ptr);
int addSetToSet(hash_set_ptr, hash_set_ptr);
int removeSetFromSet(hash_set_ptr, hash_set_ptr);
notif_line_ptr turnSetIntoNotifLines(hash_set_ptr, char *);
int sortProcesses(char *, char);
int sortMenu(int *, int *);
int createGeneralMenu(char *[], int, int *, int *);
int exitFunction(int *, int *);
WINDOW *createSubWindow(WINDOW *, int, int, int, int);
void createProcWindow(void *);
int getLinesForProc(ps_line_ptr, int *);
int addLinesToProc(WINDOW *, int, int *, int *);
int printLines(ps_line_ptr, WINDOW *, int, int, int);